 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/airports", type: :request do
  # Airport. As you add validations to Airport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Airport.create! valid_attributes
      get airports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      airport = Airport.create! valid_attributes
      get airport_url(airport)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_airport_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      airport = Airport.create! valid_attributes
      get edit_airport_url(airport)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Airport" do
        expect {
          post airports_url, params: { airport: valid_attributes }
        }.to change(Airport, :count).by(1)
      end

      it "redirects to the created airport" do
        post airports_url, params: { airport: valid_attributes }
        expect(response).to redirect_to(airport_url(Airport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Airport" do
        expect {
          post airports_url, params: { airport: invalid_attributes }
        }.to change(Airport, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post airports_url, params: { airport: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested airport" do
        airport = Airport.create! valid_attributes
        patch airport_url(airport), params: { airport: new_attributes }
        airport.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the airport" do
        airport = Airport.create! valid_attributes
        patch airport_url(airport), params: { airport: new_attributes }
        airport.reload
        expect(response).to redirect_to(airport_url(airport))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        airport = Airport.create! valid_attributes
        patch airport_url(airport), params: { airport: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested airport" do
      airport = Airport.create! valid_attributes
      expect {
        delete airport_url(airport)
      }.to change(Airport, :count).by(-1)
    end

    it "redirects to the airports list" do
      airport = Airport.create! valid_attributes
      delete airport_url(airport)
      expect(response).to redirect_to(airports_url)
    end
  end
end
